language: python

jobs:
  include:
    - name: "Python 2.7 on Linux"
      python: 2.7
    - name: "Python 3.5 on Linux"
      python: 3.5
    - name: "Python 3.6 on Linux"
      python: 3.6
    - name: "Python 3.7 on Linux"
      python: 3.7
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install -r requirements-dev.txt || pip install -r requirements-dev.txt
  - pip3 install . || pip install .

script:
  - flake8 pyss3
  - flake8 tests
  - pytest -v --cov-report=xml --cov=pyss3 tests

after_success:
  - codecov
